name: Build, validate and deploy specification
on:
  pull_request: {}
  push:
    branches: [main]
jobs:
  build:
    name: Build, Validate and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: w3c/spec-prod@v2
        with:
          TOOLCHAIN: bikeshed
          GH_PAGES_BRANCH: gh-pages
